import type { Metadata } from 'next';
import { getAllCountries } from '../services/getAllCountries';

export const metadata: Metadata = {
  title: 'Countries Layout',
  description: 'Generated by Andy',
};

export default async function CountriesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const countries = await getAllCountries();

  return (
    <div className='flex'>
      <section className='w-1/5'></section>
      <section className='bor1'>{children}</section>
    </div>
  );
}
