import type { Metadata } from 'next';
import { getAllCountries } from '../services/getAllCountries';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Countries Layout',
  description: 'Generated by Andy',
};

export default async function CountriesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const countries = await getAllCountries();

  return (
    <div className='flex'>
      <section className='w-1/5 flex flex-col gap-2 justify-center items-center border border-cyan-300'>
        {countries.map((country: any) => {
          return (
            <div key={country.id}>
              <Link href={`/countries/${country.id}`} className='link'>
                {country.name}
              </Link>
            </div>
          );
        })}
      </section>
      <section className='bor1 w-full'>{children}</section>
    </div>
  );
}
