import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Countries Layout',
  description: 'Generated by Andy',
};

export default function CountriesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='flex'>
        <section className='w-1/5'></section>
        <section className='border'></section>
    </div>
    
  );
}
